#! /bin/sh

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &

#Resolver problema de java
wmname LG3D &

$HOME/.config/polybar/forest/launch.sh

pgrep -x picom > /dev/null || picom --config /home/daniel/.config/picom/picom.conf &

feh --bg-fill ~/Imágenes/wallpapers/arco.png

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           8
#bspc config border_radius        9

#bspc config focused_border_color \#9460a3
#bspc config presel_border_color \#ffff00

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a obsidian state=floating focus=on
bspc rule -a visual-studio-code desktop='^3' follow=on
bspc rule -a Qalculate! state=floating focus=on

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
