#! /bin/sh

xsetroot -cursor_name left_ptr
pgrep -x sxhkd >/dev/null || sxhkd &

# inicializar dunst
pkill dunst
dunst -conf ~/.config/dunst/dunstrc &

#Resolver problema de java
wmname LG3D &

# Habilitar polybar
$HOME/.config/polybar/poly/launch.sh

# Run EWW.
$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &

# Run polkit daemon if doesn't started.
[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &

# Run power manager.
xfce4-power-manager &

# Run mpd if doesn't started.
[ -n "$(pidof mpd)" ] || mpd &

# Execute bspwm-specific scripts.
bspfloat &

# Iniciar picom
pgrep -x picom >/dev/null || picom --config ~/.config/picom/picom.conf &

# Colocat Fondo de pantalla
feh --bg-fill ~/Imágenes/wallpapers/arco-blue.png

bspc monitor -d 1 2 3 4 5 6

rule -a kitty follow=on focus=on
rule -a Code follow=on focus=on
rule -a firefox follow=on focus=on
rule mpv state=floating
rule feh state=floating

bspc config border_width 0
bspc config window_gap 8
#bspc config border_radius        9
#bspc config focused_border_color \#9460a3
#bspc config presel_border_color \#ffff00
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a google-chrome desktop='^2' focus=on follow=on
bspc rule -a Screenkey manage=off
bspc rule -a obsidian state=floating focus=on
bspc rule -a visual-studio-code desktop='^3' follow=on
bspc rule -a gnome-calculator state=floating focus=on
bspc rule -a Peek state=floating focus=on
